ImagingDataCommons/libdicom

- .github/workflows/run_unit_tests.yml
Override the linker rather than pinning to an old Meson version.
> workflows: use less-intrusive workaround for `LNK1107` error

- .github/workflows/run_unit_tests.yml
I believe this is the only code change needed to implement #28.  Marking as draft until the branch rename occurs; this PR should then be merged immediately afterward.
> workflows: rename master branch to main

- meson.build
Add an `override_dependency()` call for libdicom.  This is the modern way of propagating dependencies out of subprojects, allowing a parent project to use `dependency('libdicom')` rather than `dependency('libdicom', fallback : ['libdicom', 'libdicom_dep'])`.
Also skip the dist script if we're a subproject.  Dist scripts can't be used in subprojects before Meson 0.58.0, and in our case, it's not clear that it makes sense to do so.  The parent project probably doesn't want to ship our documentation, may not have vendored our dotfiles, and may not want us skipping files they did choose to vendor.
> meson: fixes for using libdicom as a subproject

- meson.build
- meson_options.txt
The `check` dependency is only needed for building tests.  Allow avoiding it by disabling tests.  However, require an explicit configuration setting to do so, and continue making `check` mandatory when tests are enabled, so users/packagers can't accidentally skip running tests when they intend to do so.
This is a partial reversal of a change I made in #23, which assumed that the wrapdb fallback made it okay to require `check`.  That's fine for end users, but requires openslide-winbuild (which doesn't use wraps from subprojects) to carry a `check` wrap even though it has no intention of running unit tests.  This PR splits the difference by making the disablement entirely manual, rather than basing it on the result of feature detection.
> meson: add option to disable tests

- include/dicom/dicom.h
- include/dicom/version.h.in
- meson.build
- src/dicom-io.c
Include `share.h` from `dicom-io.c` on Windows to fix missing definition for `_SH_DENYWR`.
Don't `dllexport`/`dllimport` when building libdicom as a static library.  In this case, we don't want callers to try to mangle our symbols to reference them from a DLL import library, and we don't want to include our symbols in the exports of a larger DLL that we might be linked into.
> Windows build fixes

- meson.build
OpenSlide supports &ge; 0.53.  The only Meson feature we use that requires > 0.50 is `meson.override_dependency()`, which can safely be skipped on older versions.
> meson: reduce minimum supported Meson version to 0.50

- meson.build
Meson 0.55 added automatic fallback to wraps in the subprojects directory, and 0.54 added the single-string argument to `fallback`.  Use the old two-argument form to properly support fallback on older Meson.
> meson: explicitly specify fallbacks for `uthash` and `check`

- include/dicom/dicom.h
- src/dicom-io.c
Remember to record the new offset when seeking.
While we're here, constify the input buffer.
> Fix memory filehandles

- include/dicom/dicom.h
A couple functions are documented to take zero-based index parameters but actually take one-based indexes.  For now, update docs to match the current API.  Should these functions be switched to zero-indexed for consistency?
> dicom.h: note some one-based indexes

- meson.build
OpenSlide supports Meson down to 0.53, which is the version in Ubuntu 20.04.  OpenSlide disables libdicom's tests when falling back to the libdicom wrap, circumventing check's requirement for a newer Meson.
This reverts commit ec925f319136d74eadb8e4c2284511b4c4acda3f.
> Revert Meson version bump to support Ubuntu 20.04

- subprojects/check.wrap
Fixes Meson warning:
WARNING: Project targets '>=0.50.0' but uses feature introduced in '0.54.1': cmakedefine without exactly two tokens.
> subprojects: update check

- tools/dcm-dump.1.in
- tools/dcm-getframe.1.in
The man pages claim to be from the `dcm` project, which is confusing. Use `libdicom` instead.
> tools: correct project name in man page footer

- meson.build
- src/dicom-file.c
We were not distinguishing between tiles and frames carefully enough.
See https://github.com/openslide/openslide/issues/484
> Revise sparse mode

- .github/workflows/codespell.yml
- .github/workflows/run_unit_tests.yml
No breaking changes.  v3 uses an old version of Node that will start [throwing deprecation warnings](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) soon.
> workflows: update actions/checkout to v4

- include/dicom/dicom.h
- meson.build
- src/dicom-dict.c
The `HAS_CONSTRUCTOR` check didn't do anything, since we tried to use `__attribute__((constructor))` whether it was defined or not.  That caused a build failure on MSVC.
Also, we shouldn't add the constructor attribute from a public header, since it's only relevant while building the library, and is conditioned on a `config.h` macro that isn't visible outside the library.  Move constructor handling directly to the one call site that needs it.
While we're here, simplify the constructor support check in `meson.build`.
> Only use `__attribute__((constructor))` if supported

- src/dicom-dict.c
Instead of duplicating an item struct's fields in the hash entry struct that wraps it, add the entire item struct as a field of the hash entry.  This eliminates casts and ensures the type system understands what we're doing.
Fixes strict aliasing violations in `dcm_init()`: we were assigning through a cast and then immediately reading through the original pointer.  This happened to cause segfaults on RHEL 9 aarch64, but any compiler would be entitled to optimize away the read.
Also rename some variables to clarify that they're not `_hash_entry` structs.
> dict: embed item structs in hash entries

- doc/requirements.txt
- doc/source/conf.py
The `libclang` package has an embedded copy of libclang, which allows us to avoid requiring the system to have a particular clang version.  This didn't work before because the `lib_search_dirs` logic in `conf.py` was clobbering a working path with a broken one.  That logic is no longer needed, so just remove it.
Tested on Fedora 38 and Ubuntu 22.04, but not specifically tested with Read the Docs.
> doc: switch back to libclang to avoid hardcoding LLVM version

- .readthedocs.yaml
- doc/requirements-rtd.txt
RTD apparently tries to use the Ubuntu `libclang.so` even though the `libclang` Python package provides its own copy.  A docs build on vanilla Ubuntu 22.04 doesn't, and it's not clear why.  Since pinning to an older `clang` Python package is known to work, use that approach in a separate `requirements-rtd.txt`.
Install the `libclang-dev` package in RTD to get the `libclang.so` symlink, so we don't have to reinstate the search logic in `conf.py`.
> doc: use a separate `requirements-rtd.txt` for Read the Docs

- README.md
Entirely optional, mostly just letting you know that `libdicom` is now also available as a Conan package.
> Add a badge for libdicom Conan package to README.md

- .github/workflows/run_unit_tests.yml
GitHub Actions runs macOS 14 on ARM64 runners.
> workflows: switch to macOS 14 beta image to get ARM64 test coverage

- CHANGELOG.md
- src/dicom-dict-build.c
- src/dicom-dict.c
`HASH_FUNCTION()` is an extension point, not part of the public API.  Use `HASH_VALUE()` instead.  The former happens to work with uthash &ge; 2.3.0, but not with older versions.
Fixes build with `uthash-static` from RHEL 8.
Also update changelog for 1.1.0 release.
> Call uthash `HASH_VALUE()` instead of `HASH_FUNCTION()`

- CHANGELOG.md
- meson.build
Certain Meson compiler checks fail if CFLAGS has `-arch x86_64 -arch arm64`.  This was causing us not to set `HAVE_UNISTD_H`, and then to fail the build on an implicit function declaration.  Detect this configuration during setup and fail with a clearer error.
https://trac.macports.org/ticket/69676
> Explicitly fail if macOS universal build is attempted

- .github/workflows/run_unit_tests.yml
It's now an alias for `macos-14`.  Switch back so we get future OS updates.
> workflows: switch back to `macos-latest`

- src/dicom-file.c
See https://github.com/ImagingDataCommons/libdicom/issues/91.  This fixes an issue where the Extended Offset Table isn't read because we skip past it.
> Stop before TAG_EXTENDED_OFFSET_TABLE so we have a chance to read it

- .github/workflows/run_unit_tests.yml
- CHANGELOG.md
- include/dicom/dicom.h
- src/dicom-file.c
Add `dcm_filehandle_get_frame_number()` to let openslide read out the perframefunctionalgroupsequence data.
Read `ConcatenationFrameOffsetNumber` and use that to offset frame fetches.
> Support dicom catenation

- .github/workflows/run_unit_tests.yml
- CHANGELOG.md
- tests/check_dicom.c
GitHub was not running tests:
Invalid workflow file: .github/workflows/run_unit_tests.yml#L82
You have an error in your yaml syntax on line 82
GCC warning:
../tests/check_dicom.c: In function ‘test_element_CS_multivalue_empty_fn’:
../tests/check_dicom.c:306:21: warning: allocation of insufficient size ‘1’ for type ‘char *’ with size ‘8’ [-Walloc-size]
> Fix unit tests in CI; fix GCC warning

- .github/workflows/run_unit_tests.yml
Public runners are [now available](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/).
> workflows: run tests on Linux ARM

- CHANGELOG.md
- src/dicom-dict-tables.h
`FrameOfReferenceToDisplayedCoordinateSystemTransformationMatrix` is 63 characters and we need room for the trailing NUL.  While the compiler would have added a trailing 0 byte anyway to maintain struct alignment, reading the string would invoke undefined behavior.
Fixes a warning on GCC 15:
../src/dicom-dict-tables.c:3296:33: warning: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (64 chars into 63 available) [-Wunterminated-string-initialization]
3296 |     {0X0070030B, DCM_VR_TAG_FD, "FrameOfReferenceToDisplayedCoordinateSystemTransformationMatrix"}
> Leave room in `_DcmAttribute` to NUL-terminate a 63-character keyword
